config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices do
	  resources :order_items
	end

  resources :invoices do
	  resources :payments
	end

  get 'reports/index' => 'reports#index'
  get 'reports/daily' => 'daily'
  get 'reports/monthly' => 'monthly'
  get 'reports/weekly' => 'weekly'
  get 'reports/comissions'=>'comissions'

  resources :deductions
  resources :stylists
  resources :businesses
  resources :subcategories
  resources :categories
  resources :products
  resources :customers
  resources :dashboard
  end
  

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    case user.role
    when 'manager'
      can :manage, :all
    when 'seller'
      alias_action :create, :read, :update, to: :cru
      can :cru, Payment
      can :cru, Customer
      can :cru, Product
      can :cru, Invoice
      can :cru, Deduction
      can :cru, Stylist
    end
  end
end
# Define abilities for the user here. For example:
#
#   return unless user.present?
#   can :read, :all
#   return unless user.admin?
#   can :manage, :all
#
# The first argument to `can` is the action you are giving the user
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on.
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, published: true
#
# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

app/models/business.rb
# frozen_string_literal: true

# Create a Business for user
class Business < ApplicationRecord
  belongs_to :user, inverse_of: :business
  has_many :stylists, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :invoices

  validates :name, presence: true
  validates :user, uniqueness: { message: 'The business has a owner' }
  validates :nit, uniqueness: { message: 'El Nit debe ser único' }
end

app/models/category.rb
# frozen_string_literal: true

# Create a category for Products
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :subcategories, dependent: :destroy
end

app/models/customer.rb
# frozen_string_literal: true

# Create a customer for business
class Customer < ApplicationRecord
  belongs_to :business
  has_many :invoices

  scope :with_name_or_dni, lambda { |customer_search|
                             where('lower(full_name) LIKE ? OR dni LIKE ?', "%#{customer_search.downcase}%",
                                   "%#{customer_search}%")
                           }
end

app/models/deduction.rb
# frozen_string_literal: true

# Create a deduction for stylist
class Deduction < ApplicationRecord
  belongs_to :stylist

  validates :date, :amount, :status, presence: true
  validates :amount, numericality: { only_integer: true, greater_than: 0 }
  validates :description, length: { maximum: 200 }
end

app/models/invoice.rb
# frozen_string_literal: true

# Create a Invoice for customer
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  accepts_nested_attributes_for :order_items
  accepts_nested_attributes_for :payments

  scope :daily_invoice, -> { where(date: Time.zone.today.all_day).order(amount: :desc) }
  scope :monthly_invoice, -> { where(date: Time.zone.today.all_month).order(amount: :desc) }
  scope :pending_invoice, -> { where(status: "pendiente")}
  scope :paid_invoice, -> { where(status: "pagado") }
  scope :partial_invoice, -> { where(status: "parcial") }
  scope :not_paid_invoice, -> { where.not(status: "pagado") }
  
  
end

app/models/order_item.rb
# frozen_string_literal: true

# Create a OrderItem for invoice
class OrderItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :product
  belongs_to :stylist
end

app/models/payment.rb
# frozen_string_literal: true

# Create a Payments for invoice
class Payment < ApplicationRecord
  belongs_to :invoice

  validates :date, :value, :kind, presence: true
  validates :value, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :note, length: { maximum: 200 }

  scope :cash_payments, -> {where( kind: "efectivo" ).sum(:value)}
  scope :card_payments, -> {where( kind: "tarjeta" ).sum(:value)} 

end

app/models/product.rb
# frozen_string_literal: true

# Create products for business
class Product < ApplicationRecord
  belongs_to :category

  validates :name, :price, presence: true
  validates :reference, uniqueness: { case_sensitive: false }, length: { minimum: 2 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cannon, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
end

app/models/stylist.rb
# frozen_string_literal: true

# Create a Stylist for business
class Stylist < ApplicationRecord
  belongs_to :business
  has_many :deductions, dependent: :destroy

  validates :dni, :name, :role, presence: true
  validates :dni, uniqueness: true

  scope :with_name_or_dni, lambda { |search|
                             where('lower(name) LIKE ? OR dni LIKE ?', "%#{search.downcase}%",
                                   "%#{search}%")
                           }
  scope :activated, -> { where('actived=true') }
end

app/models/subcategory.rb
# frozen_string_literal: true

# Create a Subcategory for categories
class Subcategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
# frozen_string_literal: true

# Create a User for application
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :business, dependent: :destroy
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

module BusinessesHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

module InvoicesHelper
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

app/views/dashboard/index.html.erb
<main>
    <div class="container-fluid px-4">
        <div class="row justify-content-md-center">
            <div class="col-xl-3 col-md-6 pt-5">
                <div class="card bg-primary text-white mb-4 pt-5">
                    <div class="card-body">Factura</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <%= link_to "Crear nueva factura", new_invoice_path, class: "small text-white stretched-link" %>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6 pt-5">
                <div class="card bg-warning text-white mb-4 pt-5">
                    <div class="card-body">Cliente</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <%= link_to "Agregar nuevo cliente", new_customer_path, class: "small text-white stretched-link" %>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">        
            <div class="col-xl-3 col-md-6 pt-5">
                <div class="card bg-success text-white mb-4 pt-5">
                    <div class="card-body">Productos</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <%= link_to "Agregar nuevo producto", new_product_path, class: "small text-white stretched-link" %>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6 pt-5">
                <div class="card bg-danger text-white mb-4 pt-5">
                    <div class="card-body">Reportes</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <%= link_to "Crear nuevo reporte", reports_index_path, class: "small text-white stretched-link" %>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>