config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices do
	  resources :order_items
	end

  resources :invoices do
	  resources :payments
	end

  get 'reports/index' => 'reports#index'
  get 'reports/daily' => 'daily'
  get 'reports/monthly' => 'monthly'
  get 'reports/weekly' => 'weekly'
  get 'reports/comissions'=>'comissions'

  resources :deductions
  resources :stylists
  resources :businesses
  resources :subcategories
  resources :categories
  resources :products
  resources :customers
  resources :dashboard
  end
  

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    case user.role
    when 'manager'
      can :manage, :all
    when 'seller'
      alias_action :create, :read, :update, to: :cru
      can :cru, Payment
      can :cru, Customer
      can :cru, Product
      can :cru, Invoice
      can :cru, Deduction
      can :cru, Stylist
    end
  end
end
# Define abilities for the user here. For example:
#
#   return unless user.present?
#   can :read, :all
#   return unless user.admin?
#   can :manage, :all
#
# The first argument to `can` is the action you are giving the user
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on.
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, published: true
#
# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

app/models/business.rb
# frozen_string_literal: true

# Create a Business for user
class Business < ApplicationRecord
  belongs_to :user, inverse_of: :business
  has_many :stylists, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :invoices

  validates :name, presence: true
  validates :user, uniqueness: { message: 'The business has a owner' }
  validates :nit, uniqueness: { message: 'El Nit debe ser único' }
end

app/models/category.rb
# frozen_string_literal: true

# Create a category for Products
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :subcategories, dependent: :destroy
end

app/models/customer.rb
# frozen_string_literal: true

# Create a customer for business
class Customer < ApplicationRecord
  belongs_to :business
  has_many :invoices

  scope :with_name_or_dni, lambda { |customer_search|
                             where('lower(full_name) LIKE ? OR dni LIKE ?', "%#{customer_search.downcase}%",
                                   "%#{customer_search}%")
                           }
end

app/models/deduction.rb
# frozen_string_literal: true

# Create a deduction for stylist
class Deduction < ApplicationRecord
  belongs_to :stylist

  validates :date, :amount, :status, presence: true
  validates :amount, numericality: { only_integer: true, greater_than: 0 }
  validates :description, length: { maximum: 200 }
end

app/models/invoice.rb
# frozen_string_literal: true

# Create a Invoice for customer
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  accepts_nested_attributes_for :order_items
  accepts_nested_attributes_for :payments

  scope :daily_invoice, -> { where(date: Time.zone.today.all_day).order(amount: :desc) }
  scope :monthly_invoice, -> { where(date: Time.zone.today.all_month).order(amount: :desc) }
  scope :pending_invoice, -> { where(status: "pendiente")}
  scope :paid_invoice, -> { where(status: "pagado") }
  scope :partial_invoice, -> { where(status: "parcial") }
  scope :not_paid_invoice, -> { where.not(status: "pagado") }
  
  
end

app/models/order_item.rb
# frozen_string_literal: true

# Create a OrderItem for invoice
class OrderItem < ApplicationRecord
  belongs_to :invoice
  belongs_to :product
  belongs_to :stylist
end

app/models/payment.rb
# frozen_string_literal: true

# Create a Payments for invoice
class Payment < ApplicationRecord
  belongs_to :invoice

  validates :date, :value, :kind, presence: true
  validates :value, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :note, length: { maximum: 200 }

  scope :cash_payments, -> {where( kind: "efectivo" ).sum(:value)}
  scope :card_payments, -> {where( kind: "tarjeta" ).sum(:value)} 

end

app/models/product.rb
# frozen_string_literal: true

# Create products for business
class Product < ApplicationRecord
  belongs_to :category

  validates :name, :price, presence: true
  validates :reference, uniqueness: { case_sensitive: false }, length: { minimum: 2 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cannon, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
end

app/models/stylist.rb
# frozen_string_literal: true

# Create a Stylist for business
class Stylist < ApplicationRecord
  belongs_to :business
  has_many :deductions, dependent: :destroy

  validates :dni, :name, :role, presence: true
  validates :dni, uniqueness: true

  scope :with_name_or_dni, lambda { |search|
                             where('lower(name) LIKE ? OR dni LIKE ?', "%#{search.downcase}%",
                                   "%#{search}%")
                           }
  scope :activated, -> { where('actived=true') }
end

app/models/subcategory.rb
# frozen_string_literal: true

# Create a Subcategory for categories
class Subcategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
# frozen_string_literal: true

# Create a User for application
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :business, dependent: :destroy
end

app/controllers/deductions_controller.rb
# frozen_string_literal: true

# Create Logic for Deductions
class DeductionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_deduction, only: %i[show edit update destroy]

  def index
    @deductions = Deduction.all
  end

  def show; end

  def new
    @deduction = Deduction.new
  end

  def edit; end

  def create
    @deduction = Deduction.new(deduction_params)

    if @deduction.save
      redirect_to deductions_url, notice: 'Deduction was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @deduction.update(deduction_params)
      redirect_to deductions_url, notice: 'Deduction was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @deduction.destroy
    redirect_to deductions_url, notice: 'Deduction was successfully destroyed.'
  end

  private

  def set_deduction
    @deduction = Deduction.find(params[:id])
  end

  def deduction_params
    params.require(:deduction).permit(:date, :amount, :stylist_id, :description, :status)
  end
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

module BusinessesHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/deductions_helper.rb
# frozen_string_literal: true

module DeductionsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

module InvoicesHelper
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

app/views/deductions/_deduction.html.erb
<div id="<%= dom_id deduction %>">
  <p>
    <strong>Date:</strong>
    <%= deduction.date %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= deduction.amount %>
  </p>

  <p>
    <strong>Stylist:</strong>
    <%= deduction.stylist_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= deduction.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= deduction.status %>
  </p>

</div>

app/views/deductions/_form.html.erb
<div class="container">
  <div class="card col-lg-4">
    <div class="card-header">
      Deducciones 
    </div>
    <div class="card-body px-2">
      <%= form_with(model: deduction) do |form| %>
      <% if deduction.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(deduction.errors.count, "error") %> prohibited this deduction from being saved:</h2>

          <ul>
            <% deduction.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row mb-3">
        <%= form.label :date, "Fecha", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.datetime_field :date, value: DateTime.now.strftime("%Y-%m-%dT%T"),  class:'form-select' %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :amount, "Cantidad", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.number_field :amount, min: 1000, step: 1000, class:"form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :stylist_id, "ID Estilista", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.collection_select :stylist_id, Stylist.order(:name), :id, :name, {}, class:'form-select' %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :description, "Descripción", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_area :description, class:"form-control", placeholder:"Descripción" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :status, "Estatus", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.select :status, ["CxC", "Descontado"], {}, { :class => 'form-select' } %>
        </div>
      </div>

      <div>
        <%= link_to "Regresar a deducciones", deductions_path, class:"btn btn-outline-secondary" %>
        <%= form.submit "Crear deducción", class:"btn btn-primary" %>
      </div>
    <% end %>    
    </div>
  </div>
</div>

app/views/deductions/edit.html.erb
<div id="deductions">
    <%= render "form", deduction: @deduction %>
</div>

app/views/deductions/index.html.erb
<div id="deductions" class="container">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-header">
					<%= link_to "Agregar Deducción", new_deduction_path, class:"btn btn-primary float-end" %>
					<h4 class="card-title">Deduccciones</h4>
				</div>
				<div class="card-body">
					<div class="table-responsive">
					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th>Fecha</th>
								<th>Valor</th>
								<th>Estilista</th>
								<th>Descripción</th>
								<th>Estado</th>
								<th>Opciones</th>
							</tr>
						</thead>
						<tbody>

						<%  @deductions.each do |deduction| %>
						<tr class="align-middle">
							<td class="py-1"> <%= deduction.date.strftime("%F %T") %> </td>
							<td> <%= deduction.amount %></td>
							<td> <%= deduction.stylist.name %> </td>
							<td> <%= deduction.description %></td>
							<td> <%= deduction.status %></td>
							<td> 
								<button type="button" class="btn btn-info">
								<%= link_to "", edit_deduction_path(deduction), class:"bi bi-pencil text-white" %> 
								</button>
								<button type="button" class="btn btn-danger">
								<%= link_to "", deduction_path(deduction),  data: {turbo_method: :delete, 
								turbo_confirm: "Are you sure?" }, class:"bi bi-trash text-white" %> 
								</button>
							</td>
						</tr>
					<% end %>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/deductions/new.html.erb
<div id="deductions">
    <%= render "form", deduction: @deduction %>
</div>

app/views/deductions/show.html.erb
<div id="deductions">
  <p style="color: green"><%= notice %></p>

  <%= render @deduction %>

  <div>
    <% if can? :cru, @deduction %>
      <%= link_to "Edit this deduction", edit_deduction_path(@deduction) %> |
    <% end %>
    <%= link_to "Back to deductions", deductions_path %>

    <% if can? :destroy, @deduction %>
      <%= button_to "Destroy this deduction", @deduction, method: :delete %>
    <% end %>
  </div>
</div>