config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices do
	  resources :order_items
	end

  resources :invoices do
	  resources :payments
	end

  get 'reports/index' => 'reports#index'
  get 'reports/daily' => 'daily'
  get 'reports/monthly' => 'monthly'
  get 'reports/weekly' => 'weekly'
  get 'reports/comissions'=>'comissions'

  resources :deductions
  resources :stylists
  resources :businesses
  resources :subcategories
  resources :categories
  resources :products
  resources :customers
  resources :dashboard
  end
  

app/models/stylist.rb
# frozen_string_literal: true

# Create a Stylist for business
class Stylist < ApplicationRecord
  belongs_to :business
  has_many :deductions, dependent: :destroy

  validates :dni, :name, :role, presence: true
  validates :dni, uniqueness: true

  scope :with_name_or_dni, lambda { |search|
                             where('lower(name) LIKE ? OR dni LIKE ?', "%#{search.downcase}%",
                                   "%#{search}%")
                           }
  scope :activated, -> { where('actived=true') }
end

app/controllers/stylists_controller.rb
# frozen_string_literal: true

# Create Logic for Stylists
class StylistsController < ApplicationController
  load_and_authorize_resource
  before_action :set_stylist, only: %i[show edit update destroy]

  def index
    if user_signed_in?
      @stylists = Stylist.where(business_id: current_user.id)
    else
      redirect_to dashboard_index_path
    end
  end

  def show; end

  def new
    @stylist = Stylist.new
  end

  def desactivate
    @stylists = Stylist.with_name_or_dni(params[:_query]) if params[:_query].present?

    Stylist.find(params[:stylist_id]).toggle(:actived).save if params[:stylist_id].present?
  end

  def edit; end

  def create
    @stylist = Stylist.new(stylist_params)

    respond_to do |format|
      if @stylist.save
        format.html { redirect_to stylists_url, notice: 'El estilista fue creado con éxito.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stylist.update(stylist_params)
        format.html { redirect_to stylists_url, notice: 'El estilista se ha actualizado con éxito.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stylist.destroy

    respond_to do |format|
      format.html { redirect_to stylists_url, notice: 'El estilista fue eliminado con éxito..' }
    end
  end

  private

  def set_stylist
    @stylist = Stylist.find(params[:id])
  end

  def stylist_params
    params.require(:stylist).permit(:dni, :name, :telephone, :actived, :role, :business_id)
  end

  def search_params
    params.require(:stylist).permit(:_query)
  end

  def desactivate_params
    params.require(:stylist).permit(:id, :_query)
  end
end

app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

app/views/stylists/_form.html.erb
<div class="container">
  <div class="card col-lg-4">
    <div class="card-header">
      Estilista
    </div>
    <div class="card-body">
      <%= form_with(model: stylist) do |form| %>
      <% if stylist.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(stylist.errors.count, "error") %> No se puede guardar este estilista: </h2>

          <ul>
            <% stylist.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row mb-3">
        <%= form.label :dni, "DNI", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_field :dni, class:"form-control", placeholder:"Documento de identidad" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :name, "Nombre", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_field :name, class:"form-control", placeholder:"Nombre y apellido" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :role, "Rol", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_field :role, class:"form-control", placeholder:"Cargo o rol" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :telephone, "Teléfono", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_field :telephone, class:"form-control", placeholder:"Teléfono" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :actived, "Activo", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.check_box :actived %>
        </div>
      </div>

          <%= form.hidden_field :business_id, value: @business.id %>
          
        <%= link_to "Regresar", stylists_path, class:"btn btn-outline-secondary" %>
        <%= form.submit "Guardar", class:"btn btn-primary" %>
      </div>
    <% end %>    
    </div>
  </div>
</div>

app/views/stylists/_stylist.html.erb
<div id="<%= dom_id stylist %>">
  <p>
    <strong>DNI:</strong>
    <%= stylist.dni %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= stylist.name %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= stylist.telephone %>
  </p>

  <p>
    <strong>Rol:</strong>
    <%= stylist.role %>
  </p>

  <p>
    <strong>Activo:</strong>
    <%= stylist.actived %>
  </p>

</div>

app/views/stylists/desactivate.html.erb
<div id="stylists">   
    <%= render "form_search"%>
</div>

app/views/stylists/edit.html.erb
  <%= render "form", stylist: @stylist %>

app/views/stylists/index.html.erb
<div id="stylists" class="container">
<div class="row">
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
      <div class="card-header">
        <%= link_to "Agregar Estilista", new_stylist_path, class:"btn btn-primary float-end" %>
        <h4 class="card-title">Colaboradores</h4>
      </div>
			<div class="card-body">
				<div class="table-responsive">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>DNI</th>
							<th>Teléfono</th>
							<th>Activo</th>
							<th>Rol</th>
							<th>Opciones</th>
						</tr>
					</thead>
					<tbody>

					<%  @stylists.each do |stylist| %>
					<tr class="align-middle">
						<td class="py-1"> 
            <%= stylist.name %> </td>
						<td> <%= stylist.dni %></td>
						<td> <%= stylist.telephone %></td>
						<td> <%= stylist.actived %> </td>
						<td> <%= stylist.role%></td>
						<td> 
              <button type="button" class="btn btn-info">
							<%= link_to "", edit_stylist_path(stylist), class:"bi bi-pencil text-white" %> 
              </button>
              <button type="button" class="btn btn-danger">
							<%= link_to "", stylist_path(stylist),  data: {turbo_method: :delete, 
								turbo_confirm: "Estás seguro?" }, class:"bi bi-trash text-white" %> 
								</button>
            </td>
					</tr>
				<% end %>

				</tbody>
			</table>
		</div>
	</div>
</div>
</div>

app/views/stylists/new.html.erb
<%= render "form", stylist: @stylist %>

app/views/stylists/show.html.erb
<div id="stylists">
  <p style="color: green"><%= notice %></p>

  <%= render @stylist %>

  <div>
  <% if can? :cru, @stylist %>
    <%= link_to "Edit this stylist", edit_stylist_path(@stylist) %> |
  <% end %>
    <%= link_to "Back to stylists", stylists_path %>

  <% if can? :destroy, @stylist %>
    <%= button_to "Destroy this stylist", @stylist, method: :delete %>
  <% end %>
  </div>
</div>