config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :invoices do
	  resources :order_items
	end

  resources :invoices do
	  resources :payments
	end

  get 'reports/index' => 'reports#index'
  get 'reports/daily' => 'daily'
  get 'reports/monthly' => 'monthly'
  get 'reports/weekly' => 'weekly'
  get 'reports/comissions'=>'comissions'

  resources :deductions
  resources :stylists
  resources :businesses
  resources :subcategories
  resources :categories
  resources :products
  resources :customers
  resources :dashboard
  end
  

app/models/payment.rb
# frozen_string_literal: true

# Create a Payments for invoice
class Payment < ApplicationRecord
  belongs_to :invoice

  validates :date, :value, :kind, presence: true
  validates :value, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :note, length: { maximum: 200 }

  scope :cash_payments, -> {where( kind: "efectivo" ).sum(:value)}
  scope :card_payments, -> {where( kind: "tarjeta" ).sum(:value)} 

end

app/controllers/payments_controller.rb
# frozen_string_literal: true

# Create Logic for Payments
class PaymentsController < ApplicationController
  load_and_authorize_resource
  before_action :get_invoice
  before_action :set_invoice_status
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = @invoice.payments
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = @invoice.payments.build
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = @invoice.payments.build(payment_params)
    Payment.new(payment_params)
    respond_to do |format|
   
      if @payment.save
        set_invoice_status
        format.html { redirect_to invoice_payments_path(@invoice), notice: 'El pago se ha realizado con éxito.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to invoice_payment_path(@invoice), notice: 'El pago se ha actualizado con éxito.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'El pago se ha eliminado con éxito.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = @invoice.payments.find(params[:id])
  end

  def get_invoice
    @invoice = Invoice.find(params[:invoice_id])
  end

  def set_invoice_status
    balance=@invoice.payments.sum(:value)
    amount=@invoice.amount
    if (amount - balance).positive?
      @invoice.update(status: "parcial")
    else
      @invoice.update(status: "pagado")
      @invoice.update(amount: balance)
    end
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:date, :invoice_id, :value, :kind, :note)
  end

  def invoice_params
    params.require(:invoice).permit(:invoice_id)
  end
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class="container ps-5">
  <div class="card col-lg-4 text-left border border-1">
    <div class="card-header text-center">
      <h1>Pagos</h1>
    </div>
    <div class="card-body px-4">
      <%= form_with(model: [ @invoice, payment]) do |form| %>
      <% if payment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(payment.errors.count, "error") %> No se puede guardar este pago:</h2>

          <ul>
            <% payment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row mb-3">
        <%= form.label "Fecha", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.datetime_field :date, value: DateTime.now.strftime("%Y-%m-%dT%T"),  class:'form-select' %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label "# Factura", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_field :invoice_id, class:"form-control", value: @invoice.id, placeholder:"Invoice ID"%>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label "Cantidad", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.number_field :value, min: 1000, step: 1000, class:"form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label "Método de pago", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.select :kind, ([['Efectivo', 'efectivo'], ['Tarjeta', 'tarjeta']]), {}, { :class => 'form-select' } %>
          </div>
      </div>

      <div class="row mb-3">
        <%= form.label "Nota", style: "display: block", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-9">
          <%= form.text_area :note, class:"form-control", placeholder:"Notas" %>
        </div>
      </div>

      <div>
        <%= link_to "Regresar", invoice_payments_path, class:"btn btn-outline-secondary" %>
        <%= form.submit "Guardar", class:"btn btn-primary" %>
      </div>
    <% end %>    
    </div>
  </div>
</div>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
<div class="container d-flex justify-center">
  <div class="card col-lg-12">
    <div class="card-header">
      Pago
    </div>
    <div class="card-body">
      <p>
        <strong>Fecha: </strong><%= payment.date %>
      </p>
      <p>
        <strong>Factura: </strong><%= payment.invoice_id %>
      </p>
      <p>
        <strong>Cantidad: </strong><%= payment.value %>
      </p>
      <p>
        <strong>Tipo de pago: </strong><%= payment.kind %>
      </p>

      <p>
        <strong>Nota: </strong><%= payment.note %>
      </p>
      </div>
    </div>
  </div>
</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<div class="px-4 py-5  text-center">
  <img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/000000/external-payments-automotive-dealership-flaticons-lineal-color-flat-icons-5.png"/>
    <div class="col-lg-6 mx-auto">
      <h1 class="display-5 fw-bold">Pago efectuado</h1>
      <p class="lead mb-4">
        Bienvenido a la seccion de pagos, por favor de click en el "continuar" para acceder al menu.
      </p>
      <p style="color: green"><%= notice %></p>
      <div id="payments" class="d-flex justify-content-center mb-4">
        <% @payments.each do |payment| %>
          <%= render payment %>
          <p>
            <%#= link_to "Show this payment", payment %>
          </p>
        <% end %>
      </div>

      <%= link_to "Continuar", new_invoice_payment_path, class:"btn btn-primary btn-lg px-4 gap-3" %>
      <%= link_to "Volver a facturas",invoices_path, class:"btn btn-outline-secondary btn-lg px-4 gap-3" %>
</div>

app/views/payments/new.html.erb
<%= render "form", payment: @payment %>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>